/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    posts: Post;
    pages: Page;
    mensagens: Mensagen;
    midia: Midia;
    categorias: Categoria;
    tags: Tag;
    autores: Autore;
    link_rules: LinkRule;
    links_gerados: LinksGerado;
    queries_log: QueriesLog;
    lojas: Loja;
    cupons: Cupon;
    ofertas: Oferta;
    produtos: Produto;
    banners: Banner;
    cliques: Clique;
    historico_desconto: HistoricoDesconto;
    categorias_oferta: CategoriasOferta;
    produtos_fisicos: ProdutosFisico;
    variantes_produto: VariantesProduto;
    ofertas_produto: OfertasProduto;
    historico_preco_oferta: HistoricoPrecoOferta;
    vinculos_catalogo: VinculosCatalogo;
    elegibilidade_cupom: ElegibilidadeCupom;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    mensagens: MensagensSelect<false> | MensagensSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    autores: AutoresSelect<false> | AutoresSelect<true>;
    link_rules: LinkRulesSelect<false> | LinkRulesSelect<true>;
    links_gerados: LinksGeradosSelect<false> | LinksGeradosSelect<true>;
    queries_log: QueriesLogSelect<false> | QueriesLogSelect<true>;
    lojas: LojasSelect<false> | LojasSelect<true>;
    cupons: CuponsSelect<false> | CuponsSelect<true>;
    ofertas: OfertasSelect<false> | OfertasSelect<true>;
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    cliques: CliquesSelect<false> | CliquesSelect<true>;
    historico_desconto: HistoricoDescontoSelect<false> | HistoricoDescontoSelect<true>;
    categorias_oferta: CategoriasOfertaSelect<false> | CategoriasOfertaSelect<true>;
    produtos_fisicos: ProdutosFisicosSelect<false> | ProdutosFisicosSelect<true>;
    variantes_produto: VariantesProdutoSelect<false> | VariantesProdutoSelect<true>;
    ofertas_produto: OfertasProdutoSelect<false> | OfertasProdutoSelect<true>;
    historico_preco_oferta: HistoricoPrecoOfertaSelect<false> | HistoricoPrecoOfertaSelect<true>;
    vinculos_catalogo: VinculosCatalogoSelect<false> | VinculosCatalogoSelect<true>;
    elegibilidade_cupom: ElegibilidadeCupomSelect<false> | ElegibilidadeCupomSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      snapshotDesconto: TaskSnapshotDesconto;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  slug: string;
  nome: string;
  /**
   * O tema da casa, em minúsculas e na forma que cabe DEPOIS de "de": "software e hospedagem", "impressão 3D". Entra no <title> da home, no manifest e no .well-known/mcp.json. Vazio, a frase simplesmente não sai (PRD 14 D4) — título curto é melhor que título de outro nicho.
   */
  nicho?: string | null;
  /**
   * exemplo.com, loja.exemplo.com — migração de domínio = trocar aqui + 301
   */
  canonical_host: string;
  /**
   * Papéis do design system (design-tokens.md v1.0.0, auditado WCAG AA). Cor é DADO do tenant: o CSS do site nunca fixa hex, senão o multi-tenant quebra.
   */
  tema: {
    /**
     * marca: header, links, títulos de seção
     */
    cor_primaria: string;
    /**
     * texto POR CIMA da cor da marca — chip ativo, CTA do cabeçalho
     */
    cor_sobre_marca?: string | null;
    cor_fundo: string;
    /**
     * SÓ o botão que leva à loja (/r/{id}) — nenhum outro elemento
     */
    cor_acao?: string | null;
    /**
     * texto dentro do botão de ação
     */
    cor_sobre_acao?: string | null;
    /**
     * o número do desconto e badges
     */
    cor_desconto?: string | null;
    /**
     * selo de verificação e checks
     */
    cor_verificado?: string | null;
    cor_texto?: string | null;
    /**
     * legendas — passa em todos os fundos suaves
     */
    cor_apoio?: string | null;
    /**
     * breadcrumb, placeholder
     */
    cor_sutil?: string | null;
    cor_superficie?: string | null;
    cor_superficie_marca?: string | null;
    /**
     * fundo do selo de verificação
     */
    cor_superficie_verificado?: string | null;
    /**
     * borda de cartão, cabeçalho, tabela e menu
     */
    cor_borda?: string | null;
    /**
     * borda tracejada do código do cupom (que É o botão de copiar)
     */
    cor_borda_codigo?: string | null;
    /**
     * acordeão de cupons expirados — nunca via opacity, que derruba o contraste
     */
    cor_superficie_expirado?: string | null;
    /**
     * aviso dentro do bloco de expirados
     */
    cor_aviso?: string | null;
    logo?: (number | null) | Midia;
    /**
     * ícone QUADRADO da aba. Separado do logo porque o logo costuma ser letreiro (largo e baixo) e letreiro em 16px é borrão — não é a mesma imagem em tamanho menor.
     */
    favicon?: (number | null) | Midia;
    icones?: {
      /**
       * vetor — navegador moderno, nítido em qualquer tamanho
       */
      svg?: (number | null) | Midia;
      /**
       * favicon.ico 32px — navegador antigo
       */
      ico?: (number | null) | Midia;
      /**
       * apple-touch-icon 180px — atalho no iOS
       */
      apple?: (number | null) | Midia;
      /**
       * manifest 192px — Android
       */
      png192?: (number | null) | Midia;
      /**
       * manifest 512px — splash da PWA
       */
      png512?: (number | null) | Midia;
    };
    /**
     * família self-hosted (PRD 02)
     */
    fonte_titulos?: string | null;
    /**
     * família self-hosted (PRD 02)
     */
    fonte_corpo?: string | null;
  };
  /**
   * PRD 12 — os MESMOS papéis, com os valores de quando o sistema do leitor está no escuro. Não é filtro sobre o claro: é dado, e passa pela mesma trava de contraste. Sem `ativo`, o site serve só o claro.
   */
  tema_escuro?: {
    /**
     * desligado, o site declara `color-scheme: light` e ignora a preferência do sistema — é o certo pra tenant cuja paleta escura ninguém curou ainda. Melhor claro do que um escuro chutado.
     */
    ativo?: boolean | null;
    /**
     * marca: header, links, títulos de seção
     */
    cor_primaria?: string | null;
    /**
     * texto POR CIMA da cor da marca — chip ativo, CTA do cabeçalho
     */
    cor_sobre_marca?: string | null;
    cor_fundo?: string | null;
    /**
     * SÓ o botão que leva à loja (/r/{id}) — nenhum outro elemento
     */
    cor_acao?: string | null;
    /**
     * texto dentro do botão de ação
     */
    cor_sobre_acao?: string | null;
    /**
     * o número do desconto e badges
     */
    cor_desconto?: string | null;
    /**
     * selo de verificação e checks
     */
    cor_verificado?: string | null;
    cor_texto?: string | null;
    /**
     * legendas — passa em todos os fundos suaves
     */
    cor_apoio?: string | null;
    /**
     * breadcrumb, placeholder
     */
    cor_sutil?: string | null;
    cor_superficie?: string | null;
    cor_superficie_marca?: string | null;
    /**
     * fundo do selo de verificação
     */
    cor_superficie_verificado?: string | null;
    /**
     * borda de cartão, cabeçalho, tabela e menu
     */
    cor_borda?: string | null;
    /**
     * borda tracejada do código do cupom (que É o botão de copiar)
     */
    cor_borda_codigo?: string | null;
    /**
     * acordeão de cupons expirados — nunca via opacity, que derruba o contraste
     */
    cor_superficie_expirado?: string | null;
    /**
     * aviso dentro do bloco de expirados
     */
    cor_aviso?: string | null;
    /**
     * OPCIONAL. Só preencha se o letreiro do tema claro for de tinta escura — aí ele some no fundo escuro. Vazio, o cabeçalho usa o logo normal, que é o caso de quem tem logo colorido ou claro.
     */
    logo?: (number | null) | Midia;
  };
  /**
   * carrega o polyfill do WebMCP em quem NÃO tem suporte nativo (~20KB, sob demanda). Desligado por padrão: sem extensão que consuma, as ferramentas registradas não são lidas por ninguém
   */
  webmcp_polyfill?: boolean | null;
  autolinker: {
    max_links_pagina: number;
    stoplist?: string[] | null;
    whitelist_cross_tenant?: (number | Tenant)[] | null;
  };
  seo: {
    gsc_property?: string | null;
    sitemap_enabled?: boolean | null;
    title_pattern_loja: string;
  };
  /**
   * IDs/tags de afiliado NUNCA no banco — aqui vai o NOME da env var
   */
  programas_ativos?:
    | {
        programa:
          | 'hostinger'
          | 'cloudways'
          | 'amazon'
          | 'shopee'
          | 'awin'
          | 'impact'
          | 'mercadolivre'
          | 'hotmart'
          | 'direto'
          | 'outro';
        /**
         * ex.: AFF_AMAZON_TAG — o valor mora no .env do web/bot
         */
        id_afiliado_env: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  credit?: string | null;
  /**
   * manifesto do alias /wp-content/uploads/
   */
  wp_url_antiga?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    cartao?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    capa?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome: string;
  roles: ('super-admin' | 'agente' | 'editor' | 'ingestao' | 'sistema')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  titulo: string;
  slug: string;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categoria?: (number | null) | Categoria;
  tags?: (number | Tag)[] | null;
  autor?: (number | null) | Autore;
  capa?: (number | null) | Midia;
  /**
   * JSON-LD extra migrado do vault (opcional)
   */
  schema_extra?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * FAQ que o WP publicava no JSON-LD; vira FAQPage no site (import:faq)
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Subtipo de Article que o WP declarava nesta URL (NewsArticle, TechArticle…). Vazio = BlogPosting. Preenchido por `import:tipo-artigo` a partir do crawl de paridade.
   */
  tipo_schema?: string[] | null;
  /**
   * auto-linker (PRD 04)
   */
  ancoras_alvo?: string[] | null;
  /**
   * data real de publicação (do WP na migração) — createdAt é a data do import
   */
  publicado_em?: string | null;
  /**
   * última atualização real do conteúdo
   */
  atualizado_em?: string | null;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  slug: string;
  descricao_seo?: string | null;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  slug: string;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores".
 */
export interface Autore {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Midia;
  /**
   * LinkedIn, GitHub etc. (fonte: perfil-maicon) — E-E-A-T
   */
  sameAs?: string[] | null;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  titulo: string;
  slug: string;
  template: 'conteudo' | 'institucional' | 'contato' | 'indice';
  corpo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * dados estruturados do template (json tipado por template — mata o base64)
   */
  dados?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ancoras_alvo?: string[] | null;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  /**
   * chave de origem: identificador ESTÁVEL do artefato que gerou este documento (ex.: vault:modelos-paginas/data/qwen3.json). Único por tenant. Não é slug, não vira URL e não muda quando o título ou o slug mudam — é isso que o torna útil como chave de upsert da esteira. Vazio em documento antigo ou feito à mão
   */
  origem?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensagens".
 */
export interface Mensagen {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  email: string;
  mensagem: string;
  /**
   * de qual página a pessoa escreveu
   */
  origem_url?: string | null;
  /**
   * a caixa de entrada é a lista de não-lidas
   */
  lida?: boolean | null;
  /**
   * preenchido pelo endpoint
   */
  user_agent?: string | null;
  /**
   * IP HASHEADO — o cru nunca é gravado (mesma regra do redirect de afiliado)
   */
  ip_hash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_rules".
 */
export interface LinkRule {
  id: number;
  tenant?: (number | null) | Tenant;
  destino:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'lojas';
        value: number | Loja;
      }
    | {
        relationTo: 'ofertas';
        value: number | Oferta;
      }
    | {
        relationTo: 'produtos';
        value: number | Produto;
      };
  ancoras_alvo: string[];
  prioridade?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas".
 */
export interface Loja {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  /**
   * usado em /cupom-{loja} e /empresa/{slug}
   */
  slug: string;
  logo?: (number | null) | Midia;
  url_site: string;
  /**
   * qual rede/programa de afiliado paga esta loja
   */
  programa:
    | 'hostinger'
    | 'cloudways'
    | 'amazon'
    | 'shopee'
    | 'awin'
    | 'impact'
    | 'mercadolivre'
    | 'hotmart'
    | 'direto'
    | 'outro';
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * visível na página + FAQPage schema
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * consumido pelo auto-linker (PRD 04)
   */
  ancoras_alvo?: string[] | null;
  /**
   * página oficial de cupons (changedetection.io)
   */
  watch_url?: string | null;
  /**
   * product_brand:{ID} — import idempotente (PRD 03)
   */
  wordpress_id?: string | null;
  slug_wp?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas".
 */
export interface Oferta {
  id: number;
  tenant?: (number | null) | Tenant;
  loja: number | Loja;
  titulo: string;
  slug: string;
  /**
   * taxonomia das ofertas do site
   */
  tipo: 'cupom' | 'credito' | 'lifetime' | 'desconto_api';
  preco?: {
    valor?: number | null;
    moeda?: string | null;
    ciclo?: ('unico' | 'mensal' | 'anual') | null;
    /**
     * quando o preço foi visto — nunca preço sem timestamp
     */
    preco_em?: string | null;
  };
  /**
   * o desconto que a LOJA já dá — alimenta o formato empilhado (spec-desconto-e-historico)
   */
  desconto_loja?: {
    valor?: number | null;
    tipo?: ('percentual' | 'valor') | null;
    moeda?: string | null;
    /**
     * quando esse desconto foi visto — obrigatório junto com o valor
     */
    verificado_em?: string | null;
    fonte?: ('site-loja' | 'programa' | 'manual') | null;
  };
  /**
   * categorias do Woo — a página /categoria-oferta/{slug} lista por aqui
   */
  categorias?: (number | CategoriasOferta)[] | null;
  cupom?: (number | null) | Cupon;
  /**
   * destino do /r/o{id} quando não há cupom (crédito, lifetime, desconto já no link)
   */
  url_afiliado_fonte?: string | null;
  /**
   * FAQ que o WP publicava no JSON-LD; vira FAQPage no site (import:faq)
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * imagem do cartão nas vitrines — sem ela o cartão vira só texto
   */
  imagem?: (number | null) | Midia;
  /**
   * a linha abaixo do H1 e no card lateral (migrada do brand_headline do WP). Escreva você — nunca saída de LLM
   */
  headline?: string | null;
  /**
   * o diferencial em uma linha, no destaque do card ("Até 70% de desconto"). É RÓTULO editorial, não medição: não vale como desconto verificado e não entra na composição — para número com data, use desconto_loja
   */
  rotulo_oferta?: string | null;
  /**
   * itens da lista de funcionalidades (migrados do benefit_bullets do WP)
   */
  beneficios?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * a linha de descrição do cartão (migrada do short_description/excerpt do WP). Escreva você — nunca saída de LLM: aqui se fala de preço e benefício
   */
  resumo?: string | null;
  /**
   * estrutura da página de lifetime (destaques, veredito, faq) — extraída do WP, nunca de LLM
   */
  dados?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * home/hubs
   */
  destaque?: boolean | null;
  /**
   * {post_type}:{ID} — import idempotente
   */
  wordpress_id?: string | null;
  slug_wp?: string | null;
  ancoras_alvo?: string[] | null;
  /**
   * chave de origem: identificador ESTÁVEL do artefato que gerou este documento (ex.: vault:modelos-paginas/data/qwen3.json). Único por tenant. Não é slug, não vira URL e não muda quando o título ou o slug mudam — é isso que o torna útil como chave de upsert da esteira. Vazio em documento antigo ou feito à mão
   */
  origem?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Taxonomia do catálogo. Só termos "canonica" viram chip; a curadoria NUNCA muda URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_oferta".
 */
export interface CategoriasOferta {
  id: number;
  tenant?: (number | null) | Tenant;
  nome: string;
  slug: string;
  /**
   * hierarquia vinda do WP
   */
  pai?: (number | null) | CategoriasOferta;
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  navegacao: 'nao_curada' | 'canonica' | 'sinonimo' | 'oculta';
  /**
   * obrigatório quando navegacao=sinonimo; aponta direto pro canônico
   */
  equivalente_a?: (number | null) | CategoriasOferta;
  /**
   * quando preenchido, vence a ordem por volume de ofertas
   */
  ordem_chip?: number | null;
  wordpress_id?: string | null;
  slug_wp?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupons".
 */
export interface Cupon {
  id: number;
  tenant?: (number | null) | Tenant;
  loja: number | Loja;
  codigo: string;
  desconto_tipo: 'percentual' | 'valor' | 'frete' | 'outro';
  desconto_valor?: number | null;
  /**
   * sobre QUAL preço o cupom incide. Varia por loja e campanha — errar isso é prometer desconto que o usuário não recebe. Desconhecido faz a composição não exibir total.
   */
  aplica_sobre: 'preco_cheio' | 'preco_ja_descontado' | 'desconhecido';
  /**
   * mínimo de compra, primeira compra etc.
   */
  condicoes?: string | null;
  /**
   * null = sem data conhecida (decay cuida)
   */
  validade?: string | null;
  /**
   * máquina de estados PRD 07
   */
  estado: 'pendente' | 'publicado' | 'expirando' | 'expirado' | 'revisao';
  /**
   * derivado de fontes[] quando a trilha existe
   */
  fontes_count: number;
  fontes?:
    | {
        origem: string;
        ts: string;
        id?: string | null;
      }[]
    | null;
  /**
   * governa a exigência do selo — ver colecoes.md
   */
  origem: 'importado' | 'agente' | 'manual';
  verificado_em?: string | null;
  metodo?: ('corroboracao' | 'api' | 'manual') | null;
  /**
   * feedback RF6 PRD 07
   */
  taxa_sucesso?: number | null;
  /**
   * destino do builder /r/{id} — link cru NUNCA em HTML/mensagem
   */
  url_afiliado_fonte?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  tenant?: (number | null) | Tenant;
  titulo: string;
  /**
   * página /p/{slug}
   */
  slug: string;
  loja: number | Loja;
  /**
   * obrigatória p/ estado indexavel
   */
  imagem?: (number | null) | Midia;
  preco?: number | null;
  preco_em?: string | null;
  cupom?: (number | null) | Cupon;
  url_afiliado_fonte: string;
  fonte_coleta: 'grupo' | 'api' | 'radar' | 'manual';
  /**
   * máquina PRD 08 — todos nascem landing noindex
   */
  estado: 'rascunho' | 'landing' | 'indexavel' | 'encerrado';
  /**
   * derivado do estado
   */
  indexavel?: boolean | null;
  /**
   * preenchido pelo serviço KGR (dono da SERP quando ~0)
   */
  kgr_allintitle?: number | null;
  gate_antithin?: {
    alternativas?: boolean | null;
    faq?: boolean | null;
    editorial?: boolean | null;
  };
  /**
   * alimentado PRD 09; job de poda lê
   */
  gsc_impressoes_90d?: number | null;
  gsc_cliques_90d?: number | null;
  ancoras_alvo?: string[] | null;
  /**
   * chave de origem: identificador ESTÁVEL do artefato que gerou este documento (ex.: vault:modelos-paginas/data/qwen3.json). Único por tenant. Não é slug, não vira URL e não muda quando o título ou o slug mudam — é isso que o torna útil como chave de upsert da esteira. Vazio em documento antigo ou feito à mão
   */
  origem?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_gerados".
 */
export interface LinksGerado {
  id: number;
  tenant?: (number | null) | Tenant;
  origem_url: string;
  destino:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'lojas';
        value: number | Loja;
      }
    | {
        relationTo: 'ofertas';
        value: number | Oferta;
      }
    | {
        relationTo: 'produtos';
        value: number | Produto;
      };
  ancora: string;
  /**
   * regra 1b — sem isto não dá pra medir nem revogar só uma classe
   */
  fonte_ancora: 'curada' | 'derivada';
  run_id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "queries_log".
 */
export interface QueriesLog {
  id: number;
  tenant?: (number | null) | Tenant;
  origem: 'chat' | 'mcp' | 'webmcp' | 'busca';
  texto: string;
  /**
   * tools/filtros usados na resposta
   */
  tools?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  achou: boolean;
  latencia_ms?: number | null;
  /**
   * só chat (inferência nossa)
   */
  custo_usd?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * rótulo interno — não aparece no site
   */
  nome: string;
  /**
   * versão larga (ex.: 970x250). O alt sai da mídia
   */
  imagem: number | Midia;
  /**
   * versão estreita (300x250). Sem ela, a larga serve as duas
   */
  imagem_mobile?: (number | null) | Midia;
  /**
   * destino do clique — sempre uma página nossa, nunca URL externa
   */
  oferta: number | Oferta;
  /**
   * um slot hoje; o campo existe pra o segundo não virar hardcode
   */
  posicao: 'home_topo';
  ativo?: boolean | null;
  /**
   * opcional — fora da janela, o banner não renderiza
   */
  inicia_em?: string | null;
  termina_em?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cliques".
 */
export interface Clique {
  id: number;
  tenant?: (number | null) | Tenant;
  tipo_doc: 'cupom' | 'oferta' | 'produto';
  doc_id: string;
  loja?: (number | null) | Loja;
  programa?: string | null;
  /**
   * vira subid no programa — liga comissão ao canal (teste F0-T1)
   */
  ref: 'pagina' | 'chat' | 'mcp' | 'grupo-wa' | 'grupo-tg' | 'outro';
  user_agent_class?: ('humano' | 'bot' | 'agente-ia') | null;
  /**
   * sha256(ip+salt) — IP puro não é armazenado
   */
  ip_hash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Série do desconto — exibir só com ≥3 meses de dado (menos que isso não é histórico, é ruído).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historico_desconto".
 */
export interface HistoricoDesconto {
  id: number;
  tenant?: (number | null) | Tenant;
  oferta: number | Oferta;
  /**
   * um registro por oferta por dia
   */
  data: string;
  /**
   * efetivo do dia (já composto quando houver)
   */
  desconto_pct: number;
  preco?: number | null;
  /**
   * qual cupom estava ativo naquele dia
   */
  cupom_codigo?: string | null;
  fonte: 'snapshot-diario' | 'import' | 'manual';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_fisicos".
 */
export interface ProdutosFisico {
  id: number;
  tenant: number | Tenant;
  nome: string;
  slug: string;
  marca: string;
  modelo: string;
  categoria: 'filamento' | 'impressora' | 'resina' | 'acessorio';
  descricao?: string | null;
  imagem?: (number | null) | Midia;
  gtin?: string | null;
  mpn?: string | null;
  especificacoes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  estado: 'draft' | 'review' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantes_produto".
 */
export interface VariantesProduto {
  id: number;
  tenant: number | Tenant;
  produto: number | ProdutosFisico;
  nome: string;
  sku_fabricante?: string | null;
  gtin?: string | null;
  material?: string | null;
  cor?: string | null;
  peso_g?: number | null;
  diametro_mm?: number | null;
  acabamento?: string | null;
  especificacoes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  imagem?: (number | null) | Midia;
  estado: 'incerta' | 'confirmada';
  chave_normalizada?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas_produto".
 */
export interface OfertasProduto {
  id: number;
  tenant: number | Tenant;
  variante: number | VariantesProduto;
  loja: number | Loja;
  seller_normalizado?: string | null;
  external_listing_id?: string | null;
  url_origem: string;
  url_afiliado?: string | null;
  url_canonica?: string | null;
  chave_listing?: string | null;
  url_redirect?: string | null;
  preco: number;
  frete?: number | null;
  disponibilidade: 'disponivel' | 'indisponivel' | 'desconhecida';
  estado: 'draft' | 'ativa' | 'encerrada';
  fonte: string;
  observado_em: string;
  validade?: string | null;
  confianca?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historico_preco_oferta".
 */
export interface HistoricoPrecoOferta {
  id: number;
  tenant: number | Tenant;
  oferta: number | OfertasProduto;
  preco: number;
  frete?: number | null;
  disponibilidade: 'disponivel' | 'indisponivel' | 'desconhecida';
  fonte: string;
  observado_em: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinculos_catalogo".
 */
export interface VinculosCatalogo {
  id: number;
  tenant: number | Tenant;
  entrada: string;
  variante: number | VariantesProduto;
  oferta?: (number | null) | OfertasProduto;
  metodo: 'gtin' | 'sku' | 'url' | 'atributos' | 'humano';
  score: number;
  evidencia:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  decisao: 'pendente' | 'confirmado' | 'rejeitado';
  observado_em: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elegibilidade_cupom".
 */
export interface ElegibilidadeCupom {
  id: number;
  tenant: number | Tenant;
  cupom: number | Cupon;
  oferta: number | OfertasProduto;
  minimo_pedido?: number | null;
  inicio?: string | null;
  fim?: string | null;
  verificado_em: string;
  fonte: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'snapshotDesconto';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'snapshotDesconto') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'mensagens';
        value: number | Mensagen;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'autores';
        value: number | Autore;
      } | null)
    | ({
        relationTo: 'link_rules';
        value: number | LinkRule;
      } | null)
    | ({
        relationTo: 'links_gerados';
        value: number | LinksGerado;
      } | null)
    | ({
        relationTo: 'queries_log';
        value: number | QueriesLog;
      } | null)
    | ({
        relationTo: 'lojas';
        value: number | Loja;
      } | null)
    | ({
        relationTo: 'cupons';
        value: number | Cupon;
      } | null)
    | ({
        relationTo: 'ofertas';
        value: number | Oferta;
      } | null)
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'cliques';
        value: number | Clique;
      } | null)
    | ({
        relationTo: 'historico_desconto';
        value: number | HistoricoDesconto;
      } | null)
    | ({
        relationTo: 'categorias_oferta';
        value: number | CategoriasOferta;
      } | null)
    | ({
        relationTo: 'produtos_fisicos';
        value: number | ProdutosFisico;
      } | null)
    | ({
        relationTo: 'variantes_produto';
        value: number | VariantesProduto;
      } | null)
    | ({
        relationTo: 'ofertas_produto';
        value: number | OfertasProduto;
      } | null)
    | ({
        relationTo: 'historico_preco_oferta';
        value: number | HistoricoPrecoOferta;
      } | null)
    | ({
        relationTo: 'vinculos_catalogo';
        value: number | VinculosCatalogo;
      } | null)
    | ({
        relationTo: 'elegibilidade_cupom';
        value: number | ElegibilidadeCupom;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  slug?: T;
  nome?: T;
  nicho?: T;
  canonical_host?: T;
  tema?:
    | T
    | {
        cor_primaria?: T;
        cor_sobre_marca?: T;
        cor_fundo?: T;
        cor_acao?: T;
        cor_sobre_acao?: T;
        cor_desconto?: T;
        cor_verificado?: T;
        cor_texto?: T;
        cor_apoio?: T;
        cor_sutil?: T;
        cor_superficie?: T;
        cor_superficie_marca?: T;
        cor_superficie_verificado?: T;
        cor_borda?: T;
        cor_borda_codigo?: T;
        cor_superficie_expirado?: T;
        cor_aviso?: T;
        logo?: T;
        favicon?: T;
        icones?:
          | T
          | {
              svg?: T;
              ico?: T;
              apple?: T;
              png192?: T;
              png512?: T;
            };
        fonte_titulos?: T;
        fonte_corpo?: T;
      };
  tema_escuro?:
    | T
    | {
        ativo?: T;
        cor_primaria?: T;
        cor_sobre_marca?: T;
        cor_fundo?: T;
        cor_acao?: T;
        cor_sobre_acao?: T;
        cor_desconto?: T;
        cor_verificado?: T;
        cor_texto?: T;
        cor_apoio?: T;
        cor_sutil?: T;
        cor_superficie?: T;
        cor_superficie_marca?: T;
        cor_superficie_verificado?: T;
        cor_borda?: T;
        cor_borda_codigo?: T;
        cor_superficie_expirado?: T;
        cor_aviso?: T;
        logo?: T;
      };
  webmcp_polyfill?: T;
  autolinker?:
    | T
    | {
        max_links_pagina?: T;
        stoplist?: T;
        whitelist_cross_tenant?: T;
      };
  seo?:
    | T
    | {
        gsc_property?: T;
        sitemap_enabled?: T;
        title_pattern_loja?: T;
      };
  programas_ativos?:
    | T
    | {
        programa?: T;
        id_afiliado_env?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  titulo?: T;
  slug?: T;
  corpo?: T;
  categoria?: T;
  tags?: T;
  autor?: T;
  capa?: T;
  schema_extra?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  tipo_schema?: T;
  ancoras_alvo?: T;
  publicado_em?: T;
  atualizado_em?: T;
  wordpress_id?: T;
  slug_wp?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  titulo?: T;
  slug?: T;
  template?: T;
  corpo?: T;
  dados?: T;
  ancoras_alvo?: T;
  wordpress_id?: T;
  slug_wp?: T;
  origem?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensagens_select".
 */
export interface MensagensSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  email?: T;
  mensagem?: T;
  origem_url?: T;
  lida?: T;
  user_agent?: T;
  ip_hash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  credit?: T;
  wp_url_antiga?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        cartao?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        capa?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  descricao_seo?: T;
  wordpress_id?: T;
  slug_wp?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  wordpress_id?: T;
  slug_wp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores_select".
 */
export interface AutoresSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  sameAs?: T;
  wordpress_id?: T;
  slug_wp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_rules_select".
 */
export interface LinkRulesSelect<T extends boolean = true> {
  tenant?: T;
  destino?: T;
  ancoras_alvo?: T;
  prioridade?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_gerados_select".
 */
export interface LinksGeradosSelect<T extends boolean = true> {
  tenant?: T;
  origem_url?: T;
  destino?: T;
  ancora?: T;
  fonte_ancora?: T;
  run_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "queries_log_select".
 */
export interface QueriesLogSelect<T extends boolean = true> {
  tenant?: T;
  origem?: T;
  texto?: T;
  tools?: T;
  achou?: T;
  latencia_ms?: T;
  custo_usd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas_select".
 */
export interface LojasSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  logo?: T;
  url_site?: T;
  programa?: T;
  descricao?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  ancoras_alvo?: T;
  watch_url?: T;
  wordpress_id?: T;
  slug_wp?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupons_select".
 */
export interface CuponsSelect<T extends boolean = true> {
  tenant?: T;
  loja?: T;
  codigo?: T;
  desconto_tipo?: T;
  desconto_valor?: T;
  aplica_sobre?: T;
  condicoes?: T;
  validade?: T;
  estado?: T;
  fontes_count?: T;
  fontes?:
    | T
    | {
        origem?: T;
        ts?: T;
        id?: T;
      };
  origem?: T;
  verificado_em?: T;
  metodo?: T;
  taxa_sucesso?: T;
  url_afiliado_fonte?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas_select".
 */
export interface OfertasSelect<T extends boolean = true> {
  tenant?: T;
  loja?: T;
  titulo?: T;
  slug?: T;
  tipo?: T;
  preco?:
    | T
    | {
        valor?: T;
        moeda?: T;
        ciclo?: T;
        preco_em?: T;
      };
  desconto_loja?:
    | T
    | {
        valor?: T;
        tipo?: T;
        moeda?: T;
        verificado_em?: T;
        fonte?: T;
      };
  categorias?: T;
  cupom?: T;
  url_afiliado_fonte?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  corpo?: T;
  imagem?: T;
  headline?: T;
  rotulo_oferta?: T;
  beneficios?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  resumo?: T;
  dados?: T;
  destaque?: T;
  wordpress_id?: T;
  slug_wp?: T;
  ancoras_alvo?: T;
  origem?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  tenant?: T;
  titulo?: T;
  slug?: T;
  loja?: T;
  imagem?: T;
  preco?: T;
  preco_em?: T;
  cupom?: T;
  url_afiliado_fonte?: T;
  fonte_coleta?: T;
  estado?: T;
  indexavel?: T;
  kgr_allintitle?: T;
  gate_antithin?:
    | T
    | {
        alternativas?: T;
        faq?: T;
        editorial?: T;
      };
  gsc_impressoes_90d?: T;
  gsc_cliques_90d?: T;
  ancoras_alvo?: T;
  origem?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  imagem?: T;
  imagem_mobile?: T;
  oferta?: T;
  posicao?: T;
  ativo?: T;
  inicia_em?: T;
  termina_em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cliques_select".
 */
export interface CliquesSelect<T extends boolean = true> {
  tenant?: T;
  tipo_doc?: T;
  doc_id?: T;
  loja?: T;
  programa?: T;
  ref?: T;
  user_agent_class?: T;
  ip_hash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historico_desconto_select".
 */
export interface HistoricoDescontoSelect<T extends boolean = true> {
  tenant?: T;
  oferta?: T;
  data?: T;
  desconto_pct?: T;
  preco?: T;
  cupom_codigo?: T;
  fonte?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_oferta_select".
 */
export interface CategoriasOfertaSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  pai?: T;
  descricao?: T;
  navegacao?: T;
  equivalente_a?: T;
  ordem_chip?: T;
  wordpress_id?: T;
  slug_wp?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_fisicos_select".
 */
export interface ProdutosFisicosSelect<T extends boolean = true> {
  tenant?: T;
  nome?: T;
  slug?: T;
  marca?: T;
  modelo?: T;
  categoria?: T;
  descricao?: T;
  imagem?: T;
  gtin?: T;
  mpn?: T;
  especificacoes?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantes_produto_select".
 */
export interface VariantesProdutoSelect<T extends boolean = true> {
  tenant?: T;
  produto?: T;
  nome?: T;
  sku_fabricante?: T;
  gtin?: T;
  material?: T;
  cor?: T;
  peso_g?: T;
  diametro_mm?: T;
  acabamento?: T;
  especificacoes?: T;
  imagem?: T;
  estado?: T;
  chave_normalizada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas_produto_select".
 */
export interface OfertasProdutoSelect<T extends boolean = true> {
  tenant?: T;
  variante?: T;
  loja?: T;
  seller_normalizado?: T;
  external_listing_id?: T;
  url_origem?: T;
  url_afiliado?: T;
  url_canonica?: T;
  chave_listing?: T;
  url_redirect?: T;
  preco?: T;
  frete?: T;
  disponibilidade?: T;
  estado?: T;
  fonte?: T;
  observado_em?: T;
  validade?: T;
  confianca?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historico_preco_oferta_select".
 */
export interface HistoricoPrecoOfertaSelect<T extends boolean = true> {
  tenant?: T;
  oferta?: T;
  preco?: T;
  frete?: T;
  disponibilidade?: T;
  fonte?: T;
  observado_em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinculos_catalogo_select".
 */
export interface VinculosCatalogoSelect<T extends boolean = true> {
  tenant?: T;
  entrada?: T;
  variante?: T;
  oferta?: T;
  metodo?: T;
  score?: T;
  evidencia?: T;
  decisao?: T;
  observado_em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "elegibilidade_cupom_select".
 */
export interface ElegibilidadeCupomSelect<T extends boolean = true> {
  tenant?: T;
  cupom?: T;
  oferta?: T;
  minimo_pedido?: T;
  inicio?: T;
  fim?: T;
  verificado_em?: T;
  fonte?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSnapshotDesconto".
 */
export interface TaskSnapshotDesconto {
  input?: unknown;
  output: {
    criados?: number | null;
    atualizados?: number | null;
    sem_percentual?: number | null;
    falhas?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}